/**
 * node-wegene
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/19/2016
 */

var request = require('../Http/Client/RequestClient'),
    configuration = require('../configuration'),
    APIHelper = require('../APIHelper');

var Sport = {

    /**
     * Sports advice based on genetic and individual information
     * @param {string} profileId    Required parameter: Genetic profile Id
     * @param {string} sex    Required parameter: Sex of the user
     * @param {int} age    Required parameter: Age of the user
     * @param {int} height    Required parameter: Height of the user
     * @param {int} weight    Required parameter: Weight of the user
     * @param {string} healthTarget    Required parameter: Target for sport, only supporting slimming now
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {SportAdvice}
     */
    getAdvice : function(profileId, sex, age, height, weight, healthTarget, callback){
        //Assign default values
        healthTarget = healthTarget || "slimming";

        //prepare query string for API call;
        var baseUri = configuration.BASEURI;

        var queryBuilder = baseUri + "/sport/advise/{profile_id}";

        //Process template parameters
        queryBuilder = APIHelper.appendUrlWithTemplateParameters(queryBuilder, {
            "profile_id" : profileId
        });

        //validate and preprocess url
        var queryUrl = APIHelper.cleanUrl(queryBuilder);

        //prepare headers
        var headers = {
            "accept" : "application/json",
            "Authorization" : "Bearer " + configuration.oAuthAccessToken
        };

        //prepare form data
        var form = {
            "age" : age,
            "health_target" : healthTarget,
            "height" : height,
            "sex" : sex,
            "weight" : weight
        };

        //Remove null values
        APIHelper.cleanObject(form);

        //Construct the request
        var options = {
            queryUrl: queryUrl,
            method: "POST",
            headers: headers,
            form : form,
        };

        //Build the response processing.
        function cb(error, response, context) {
            if(error){
                callback({errorMessage: error.message, errorCode: error.code},null,context);
            }else if (response.statusCode >= 200 && response.statusCode <= 206) {
                callback(null,JSON.parse(response.body),context);
            }else{
                //Error handling using HTTP status codes
                callback({errorMessage: "HTTP Response Not OK", errorCode: response.statusCode, errorResponse:response.body},null,context);
            }
        }
        request(options, cb);

    }

};

module.exports = Sport;
