/**
 * WegeneAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/19/2016
 */

var request = require('../Http/Client/RequestClient'),
    configuration = require('../configuration'),
    APIHelper = require('../APIHelper');

var User = {

    /**
     * Endpoint for basic user information
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {User}
     */
    getUser : function(callback){

        //prepare query string for API call;
        var baseUri = configuration.BASEURI;

        var queryBuilder = baseUri + "/user/";

        //validate and preprocess url
        var queryUrl = APIHelper.cleanUrl(queryBuilder);

        //prepare headers
        var headers = {
            "accept" : "application/json",
            "Authorization" : "Bearer " + configuration.oAuthAccessToken
        };

        //Construct the request
        var options = {
            queryUrl: queryUrl,
            method: "GET",
            headers: headers,
        };

        //Build the response processing.
        function cb(error, response, context) {
            if(error){
                callback({errorMessage: error.message, errorCode: error.code},null,context);
            }else if (response.statusCode >= 200 && response.statusCode <= 206) {
                callback(null,JSON.parse(response.body),context);
            }else{
                //Error handling using HTTP status codes
                callback({errorMessage: "HTTP Response Not OK", errorCode: response.statusCode, errorResponse:response.body},null,context);
            }
        }
        request(options, cb);

    }

};

module.exports = User;
