/**
 * WegeneAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/19/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "https://api.wegene.com",

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the OAuthAccessToken with an appropriate value
    oAuthAccessToken : "TODO: Replace"

};

module.exports = configuration;

